### ISSUE TITLE
Error Code 499 - Login Error

### ISSUE THREAD

**Issue by jcchikikomori** [jcchikikomori/GmsCoreHuawei#3]
Stacktrace
```
2020-11-06 21:43:48.402 23510-23832/com.google.android.gms I/hwschromium-390: [INFO:network_service_network_delegate.cc(98)] resource : https://*** error code: 499
2020-11-06 21:43:48.413 23510-23510/com.google.android.gms D/GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/signinconsent?source=android&xoauth_display_name=Android%20Device&lang=en&cc=ph&langCountry=en_ph&hl=en-PH&tmpl=new_account&flowName=EmbeddedSetupAndroid&cid=3&TL=AM3QAYYejV4VQll2OMOAbUs5OSJxYxojVISWXsCM6ThBAGPiYg09BzcN2zxc5Vn2&lid=2#close
2020-11-06 21:43:48.430 23510-24232/com.google.android.gms D/GmsHttpFormClient: -- Request --
    add_account=1&androidId=387a6dceadaac0e5&app=com.google.android.gms&client_sig=38918a453d07199354f8b19af05ec6562ced5788&callerPkg=com.google.android.gms&callerSig=38918a453d07199354f8b19af05ec6562ced5788&device_country=ph&get_accountid=1&google_play_services_version=203915000&ACCESS_TOKEN=1&lang=en_PH&operatorCountry=ph&sdk_version=29&service=ac2dm&Token=oauth2_4%2F0AfDhmrjJKnoh0i7GpJNM-hFXPObdM4PB9bmwb8okepLp7wFwmmXYovaHknwkxNgkabM_SA
2020-11-06 21:43:48.692 23510-24232/com.google.android.gms W/GmsAuthLoginBrowser: onException
    java.io.IOException: Error=ServerError
        at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:95)
        at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:198)
        at java.lang.Thread.run(Thread.java:929)
```

**Comment by jcchikikomori** [comment]
Will be using @YTVanced's codebase

**Comment by jcchikikomori** [comment]
Login works, however unable to detect logged-in accounts (non-system)
Reference: #5

**Comment by jcchikikomori** [comment]
Will close for now since the core of this issue is already fixed
